name: Run Trading Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"  # يشغّله كل 15 دقيقة

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python main.py
